name: go-es
mode: local
port: 7001
debug: true
timezone: Asia/Shanghai
log:
  level: debug
  type: single
  filename: storage/logs/logs.log
  maxSize: 64
  maxAge: 7
  maxBackup: 5
  compress: false
database:
  driver: mysql
  host: 127.0.0.1
  port: 33069
  database: go-es
  username: root
  password: PXDN93VRKUm8TeE7
  charset: utf8mb4
  maxOpenConnections: 100
  maxIdleConnections: 25
  maxLifeSeconds: 300
jwt:
  secret: zBqYyQrPNaIUsnRhsGtHLivjqiMjBVLS
  expireTime: 3600
  maxRefreshTime: 86400
redis:
  host: localhost
  port: 36379
  username:
  password: G62m50oigInC30sf
  database: 0
